### ISSUE TITLE
update Dresden collection to remove markdown

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub-collections#24]
@haesleinhuepf Unfortunately, we're not going to be able to support Markdown markup when we launch Collections on the napari hub next week.

I've created an issue to track this here: https://github.com/chanzuckerberg/napari-hub/issues/738

We're going to need to reformat your Dresden collection to improve the formatting before Nov 17.

You can open another PR to make these changes yourself or we can do it for you, whichever you prefer.

Note, you can preview your Collection here: https://staging.napari-hub.org/collections/dresden

**Comment by haesleinhuepf** [comment]
No problem @neuromusic 

> Unfortunately, we're not going to be able to support Markdown markup when we launch Collections on the napari hub next week.

Would HTML work I stead? 🙃

**Comment by neuromusic** [comment]
🤔
