### ISSUE TITLE
collection idea: "napari plugins that work well with OME-Zarr"

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub-collections#38]
cc @jluethi @dgmccart

**Comment by manasaV3** [comment]
We are archiving this repository as a part of [the deprecation of collections on napari-hub](https://github.com/chanzuckerberg/napari-hub/discussions/1215). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
